// Generated by CoffeeScript 1.9.1
(function() {
  var FinalScreen;

  Candy.FinalScreen = FinalScreen = (function() {
    function FinalScreen(game) {
      this.fontStyle = {
        font: '30px Arial Bold Italic',
        fill: '#003791'
      };
      this.fontStyle1 = {
        font: '36px Arial Bold Italic',
        fill: '#003791'
      };
      return;
    }

    FinalScreen.prototype.create = function() {
      this.add.sprite(0, 0, 'background');
      this.add.text(190, 80, "Maximum possible score :", this.fontStyle);
      this.add.text(570, 80, Candy.words[Candy.wordIndex].length, this.fontStyle);
      this.add.text(270, 200, "You Scored :", this.fontStyle1);
      this.add.text(500, 200, Candy._score, this.fontStyle1);
      this.add.button(180, 350, 'iconsWithText', this.tryAgain, this, 'tryAgainIcon.png', 'tryAgainIcon.png', 'tryAgainIcon.png', 'tryAgainIcon.png');
      this.add.button(350, 350, 'iconsWithText', this.nextWord, this, 'nextWordIcon.png', 'nextWordIcon.png', 'nextWordIcon.png', 'nextWordIcon.png');
      this.add.button(520, 350, 'iconsWithText', this.mainMenu, this, 'mainMenuIcon.png', 'mainMenuIcon.png', 'mainMenuIcon.png', 'mainMenuIcon.png');
    };

    FinalScreen.prototype.tryAgain = function() {
      this.state.start('Play');
    };

    FinalScreen.prototype.nextWord = function() {
      Candy.wordIndex++;
      this.state.start('Play');
    };

    FinalScreen.prototype.mainMenu = function() {
      this.state.start('MainMenu');
    };

    return FinalScreen;

  })();

}).call(this);
