// Generated by CoffeeScript 1.9.1
(function() {
  var Help;

  Candy.Help = Help = (function() {
    function Help() {}

    Help.prototype.create = function() {
      this.add.sprite(0, 0, 'instructions');
      this.add.button(50, 30, 'icons', this.back, this, 'backIcon.png', 'backIcon.png', 'backIcon.png', 'backIcon.png');
    };

    Help.prototype.back = function() {
      this.state.start('MainMenu');
    };

    return Help;

  })();

}).call(this);
