// Generated by CoffeeScript 1.9.1
(function() {
  var HighScores;

  Candy.HighScores = HighScores = (function() {
    function HighScores() {}

    HighScores.prototype.create = function() {
      this.add.sprite(0, 0, 'highscoresScreen');
      this.add.button(50, 30, 'icons', this.back, this, 'backIcon.png', 'backIcon.png', 'backIcon.png', 'backIcon.png');
    };

    HighScores.prototype.back = function() {
      this.state.start('MainMenu');
    };

    return HighScores;

  })();

}).call(this);
