// Generated by CoffeeScript 1.9.1
(function() {
  var MainMenu;

  Candy.MainMenu = MainMenu = (function() {
    function MainMenu() {}

    MainMenu.prototype.create = function() {
      this.add.sprite(0, 0, 'background');
      this.add.sprite(0, 0, 'letterfall');
      this.add.button(310, 380, 'buttons', this.startGame, this, 'play.png', 'play.png', 'play.png', 'play.png');
      this.add.button(310, 450, 'buttons', this.highScore, this, 'highscores.png', 'highscores.png', 'highscores.png', 'highscores.png');
      return this.add.button(310, 520, 'buttons', this.help, this, 'help.png', 'help.png', 'help.png', 'help.png');
    };

    MainMenu.prototype.startGame = function() {
      this.game.state.start('Play');
    };

    MainMenu.prototype.highScore = function() {
      this.game.state.start('HighScores');
    };

    MainMenu.prototype.help = function() {
      this.game.state.start('Help');
    };

    return MainMenu;

  })();

}).call(this);
