// Generated by CoffeeScript 1.9.1
(function() {
  var Preloader;

  Candy.Preloader = Preloader = (function() {
    function Preloader(game) {
      this.GAME_WIDTH = 800;
      this.GAME_HEIGHT = 600;
      return;
    }

    Preloader.prototype.create = function() {
      this.state.start('MainMenu');
    };

    Preloader.prototype.preload = function() {
      this.add.sprite(0, 0, 'background');
      this.add.sprite(0, 0, 'letterfall');
      this.preloadBar = this.add.sprite(this.GAME_WIDTH - 600, this.GAME_HEIGHT - 250, 'preloaderBar');
      this.game.load.setPreloadSprite(this.preloadBar);
      this.game.load.image('instructions', 'img/instructions.png');
      this.game.load.image('bomb', 'img/bomb.png');
      this.game.load.image('oops', 'img/oops.png');
      this.game.load.image('highscoresScreen', 'img/highscoresScreen.png');
      this.game.load.atlasJSONHash('alphabets', 'img/alphabets.png', 'img/alphabets.json');
      this.game.load.atlasJSONHash('buttons', 'img/buttons.png', 'img/buttons.json');
      this.game.load.atlasJSONHash('iconsWithText', 'img/iconsWithText.png', 'img/iconsWithText.json');
      this.game.load.atlasJSONHash('icons', 'img/icons.png', 'img/icons.json');
      this.game.load.atlasJSONHash('elements', 'img/elements.png', 'img/elements.json');
      this.game.load.spritesheet('player', 'img/playerSprite.png', 40, 60, 8);
    };

    return Preloader;

  })();

}).call(this);
